# Generated by Django 6.0.1 on 2026-03-05 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alumniprofile_facultyprofile_mentorshiprequest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorshiprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='suspensionlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FACULTY_APPROVED', 'Faculty_Approved'), ('ADMIN_APPROVED', 'Admin_Approved'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='mentorshiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('student', 'alumni'), name='unique_pending_request'),
        ),
    ]
