# Generated by Django 6.0.1 on 2026-03-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_mentorshiprequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
