# Generated by Django 6.0.1 on 2026-03-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_alumniprofile_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
