# Generated by Django 6.0.1 on 2026-04-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_verificationrequest_status_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
