# Generated by Django 6.0.1 on 2026-04-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_about_studentprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
