# Generated by Django 6.0.1 on 2026-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='verificationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='unique_pending_verification_request'),
        ),
    ]
