# Generated by Django 6.0.1 on 2026-06-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_verificationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspensionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='designation',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='current_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='current_join_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='past_company_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Past Institution/Company 1'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='past_company_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Past Institution/Company 2'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='past_designation_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='past_designation_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='past_timeline_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='past_timeline_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='research_publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspensionlog',
            name='duration_days',
            field=models.IntegerField(blank=True, choices=[(15, '15 Days'), (30, '30 Days'), (45, '45 Days'), (60, '60 Days')], null=True),
        ),
        migrations.AddField(
            model_name='suspensionlog',
            name='evidence',
            field=models.TextField(blank=True, help_text='Screenshots, complaint references, proof etc.'),
        ),
        migrations.AddField(
            model_name='suspensionlog',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='accounts.institution'),
        ),
        migrations.AddField(
            model_name='suspensionlog',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspensionlog',
            name='suspension_type',
            field=models.CharField(blank=True, choices=[('TEMPORARY', 'Temporary'), ('PERMANENT', 'Permanent')], max_length=20, null=True),
        ),
    ]
