# Generated by Django 6.0.1 on 2026-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_suspensionlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
