# Generated by Django 6.0.1 on 2026-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_facultyprofile_about_facultyprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='graduation_year',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='batch1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='current_join_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='past_company_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Past Institution/Company 1'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='past_company_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Past Institution/Company 2'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='past_degree_course1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Past Degree/Course'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='past_designation_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='past_designation_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='past_timeline_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='past_timeline_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='past_university1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Past Institution Name'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='recent_degree',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Past Degree/Course'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
