# Generated by Django 6.0.1 on 2026-07-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='abc_apaar_id',
            field=models.CharField(default='', max_length=50, verbose_name='ABC / APAAR ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='degree_certificate',
            field=models.ImageField(default='', upload_to='verification_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='degree_course',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='father_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
