# Generated by Django 6.0.1 on 2026-07-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_mentorshipsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipsession',
            name='active_users_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorshipsession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15),
        ),
    ]
