# Generated by Django 6.0.1 on 2026-07-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023 mentorshiprequest ended at and more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, help_text='Set when an unverified alumni account is banned. If still unverified after this date, the account is deleted.', null=True),
        ),
    ]
