# Generated by Django 6.0.1 on 2026-07-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_banned_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipsession',
            name='active_users_count',
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='creator_in_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='participant_in_room',
            field=models.BooleanField(default=False),
        ),
    ]